{% set name = "pymirc" %}
{% set version = "0.30.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymirc-{{ version }}.tar.gz
  sha256: ac324666027f83fc37d409277c51eb1f67fcbe63a62d94e38e71c537d90f3a29

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15
    - scipy >=1.1
    - matplotlib-base >=2.2.2
    - pydicom >=2.0
    - scikit-image >=0.14
    - numba >=0.39
    - nibabel >=3.0

test:
  imports:
    - pymirc
    - pymirc.fileio
    - pymirc.viewer
    - pymirc.metrics
    - pymirc.image_operations
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gschramm/pymirc
  summary: Python imaging utilities developed in the medical imaging research center of KU Leuven
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
